### ISSUE TITLE
评论区...??

### ISSUE THREAD

**Issue by ArknightsTexas** [gordonwalkedby/blog3#1]
~~大佬~~巨佬好，hexo没有评论区，那...可以把这当评论区吗 :P

**Comment by gordonwalkedby** [comment]
;w; 我不是佬（
你有什么要评论了吗
主要是如果我放个评论区，怕有人闹事我不好管，发广告或者发一些仇恨言论什么的。
（惰政表现

**Comment by ArknightsTexas** [comment]
> ;w; 我不是佬（
> 你有什么要评论吗
> 主要是如果我放个评论区，怕有人闹事我不好管，发广告或者发一些仇恨言论什么的。
> （惰政表现

不，你是佬，因为听说~~大佬~~巨佬会玩模型w
能发一篇相关的教程吗w

**Comment by gordonwalkedby** [comment]
不要啦 QAQ
你指的是怎么给起源游戏做模型吗（
那些在 valve developer wiki 有（英文的

**Comment by ArknightsTexas** [comment]
> 不要啦 QAQ
> 你指的是怎么给起源游戏做模型吗（
> 那些在 valve developer wiki 有（英文的

理 解 不 能 w

**Comment by gordonwalkedby** [comment]
很明显，那我帮不了你了。
